### ISSUE TITLE
DESCRIPTION.rst not found issue

### ISSUE THREAD

**Issue by nmadhire** [sorreltree/multienum#1]
Hi,

I am getting the DESCRIPTION.rst file not found error while installing multienum on python 2.7.9

Can you please tell me how to fix this?

Below is the log from pip install

Downloading/unpacking MultiEnum
  Getting page https://pypi.python.org/simple/MultiEnum/
  URLs to search for versions for MultiEnum:
- https://pypi.python.org/simple/MultiEnum/
  Analyzing links from page https://pypi.python.org/simple/multienum/
    Skipping https://pypi.python.org/packages/3.4/m/multienum/multienum-0.2-py3-none-any.whl#md5=14a2572e143ab9ccde7016a9e6d794b7 (from https://pypi.python.org/simple/multienum/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3.4/m/multienum/multienum-0.2.1-py3-none-any.whl#md5=f6d78b6441e29ba107fd0edb0e3121bf (from https://pypi.python.org/simple/multienum/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cp34/m/multienum/multienum-0.1b-cp34-cp34m-macosx_10_6_intel.whl#md5=0c2bcb644b37949c896b894860761dd3 (from https://pypi.python.org/simple/multienum/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/py3/m/multienum/multienum-0.1-py3-none-any.whl#md5=bac7f7189f200c52aec11dbb7fb86439 (from https://pypi.python.org/simple/multienum/) because it is not compatible with this Python
    Found link https://pypi.python.org/packages/source/m/multienum/multienum-0.1.tar.gz#md5=8de89701040779f958343a654d8b7035 (from https://pypi.python.org/simple/multienum/), version: 0.1
    Found link https://pypi.python.org/packages/source/m/multienum/multienum-0.1b.tar.gz#md5=2df5a458daed2f6a443c8e38d2907254 (from https://pypi.python.org/simple/multienum/), version: 0.1b
    Found link https://pypi.python.org/packages/source/m/multienum/multienum-0.2.tar.gz#md5=ee17c7deea5c2356dda30c83658db5d1 (from https://pypi.python.org/simple/multienum/), version: 0.2
  Ignoring link https://pypi.python.org/packages/source/m/multienum/multienum-0.1b.tar.gz#md5=2df5a458daed2f6a443c8e38d2907254 (from https://pypi.python.org/simple/multienum/), version 0.1b is a pre-release (use --pre to allow).
  Using version 0.2 (newest of versions: 0.2, 0.1)
  Downloading multienum-0.2.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/m/multienum/multienum-0.2.tar.gz#md5=ee17c7deea5c2356dda30c83658db5d1 (from https://pypi.python.org/simple/multienum/)
  Running setup.py (path:c:\users\nmadhire\appdata\local\temp\pip_build_nmadhire\MultiEnum\setup.py) egg_info for package MultiEnum
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\nmadhire\appdata\local\temp\pip_build_nmadhire\MultiEnum\setup.py", line 23, in <module>
        with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "C:\Python27\lib\codecs.py", line 878, in open
        file = **builtin**.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'c:\users\nmadhire\appdata\local\temp\pip_build_nmadhire\MultiEnum\DESCRIPTION.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  
  File "<string>", line 17, in <module>
  
  File "c:\users\nmadhire\appdata\local\temp\pip_build_nmadhire\MultiEnum\setup.py", line 23, in <module>
  
    with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
  
  File "C:\Python27\lib\codecs.py", line 878, in open
  
    file = **builtin**.open(filename, mode, buffering)

IOError: [Errno 2] No such file or directory: 'c:\users\nmadhire\appdata\local\temp\pip_build_nmadhire\MultiEnum\DESCRIPTION.rst'

**Comment by sorreltree** [comment]
Effectively a Manifest problem.  Cleaned up.
